### ISSUE TITLE
Quality setting cannot apply to embedded videos anymore

### ISSUE THREAD

**Issue by ghost** [dessant/youtube-video-quality#12] opened 2020-10-12 07:11 UTC
**System**

* OS name: Debian
* OS version: Bullseye
* Browser name: Firefox ESR
* Browser version: 78
* Extension version: 1.0.0

**Bug description**
Title says it all. I found similar extension and it is working perfectly on embedded videos. I like to use your extension because it only does what I need.

**Comment by dessant** [comment] 2020-10-12 07:27
Could you share a page with the embedded video where the issue is reproducible? Please also right-click and click on copy debug info, then share it here.

I've just tested an embedded video on this page and the quality is set to 1080p:

http://www.simplehtmlguide.com/livedemo.php?e=youtube2

**Comment by ghost** [comment] 2020-10-15 09:49
Here I set the quality to 360p and does not persist to other videos on the website: 
https://topdocumentaryfilms.com/super-comet/

Debug Info:
`{
  "ns": "yt",
  "el": "embedded",
  "cpn": "d-4OLAcJ5MlWhj0W",
  "docid": "V86G03930Nc",
  "ver": 2,
  "referrer": "https://www.youtube-nocookie.com/embed/videoseries?list=PL_IlIlrxhtPPFEYyONqefTjj3RhFk11FH&iv_load_policy=3&cc_load_policy=1&autoplay=1",
  "cmt": "1.108",
  "ei": "LhqIX86JOc_ggQOeqoCYBA",
  "fmt": "397",
  "fs": "0",
  "rt": "11.266",
  "of": "qk2cd8UfIKsXMQxAufyw6w",
  "euri": "https://topdocumentaryfilms.com/super-comet/",
  "lact": 5,
  "cl": "336570582",
  "mos": 0,
  "state": "4",
  "vm": "CAEQARgEKix4OW1PdHZBSG5zSklGcEV4VjNmanlOQXZneUZITmNBWmFVS3RaeHlCOFU0PToyQU9HdF9PS3RzZVRqMzd3RTRWY3pfWW0xeFBPU2g2bFRoaERNRTBPdDZFUFZrQS1HNXc",
  "volume": 100,
  "c": "WEB_EMBEDDED_PLAYER",
  "cver": "20201014",
  "cplayer": "UNIPLAYER",
  "cbr": "Firefox",
  "cbrver": "78.0",
  "cos": "X11",
  "autoplay": "1",
  "delay": 4,
  "hl": "en_US",
  "cr": "PH",
  "len": "2959.141",
  "fexp": "23744176,23748147,23804281,23839597,23856950,23857949,23868989,23880043,23882503,23884386,23895671,23911055,23915654,23915993,23918597,23924436,23926782,23928508,23930220,23934970,23935843,23938214,23942338,23942634,23942770,23944779,23945480,23946420,23946753,23947698,23948424,23948841,23948944,23948944,23949705,23950022,23954462,23956803,23957694,23958693,9405960,9449243",
  "list": "PL_IlIlrxhtPPFEYyONqefTjj3RhFk11FH",
  "afmt": "251",
  "size": "427:760:1.5",
  "inview": "1",
  "vct": "1.108",
  "vd": "2959.141",
  "vpl": "0.000-1.108",
  "vbu": "0.000-20.001",
  "vpa": "1",
  "vsk": "0",
  "ven": "0",
  "vpr": "1",
  "vrs": "4",
  "vns": "2",
  "vec": "null",
  "vemsg": "",
  "vvol": "1",
  "vdom": "1",
  "vsrc": "1",
  "vw": 760,
  "vh": 427,
  "creationTime": 13634,
  "totalVideoFrames": 28,
  "droppedVideoFrames": 0,
  "lct": "1.108",
  "lsk": false,
  "lmf": false,
  "lbw": "127965.196",
  "lhd": "0.742",
  "lst": "7303.447",
  "laa": "itag=251,type=3,seg=1,range=202070-267345,time=14.9-20.0,off=61574,len=65276,end=1",
  "lva": "itag=397,type=3,seg=5,range=542581-578653,time=25.6-30.7,off=0,len=36073,end=1",
  "lar": "itag=251,type=3,seg=2,range=267346-394597,time=20.0-30.0,off=0,len=127252,end=1",
  "lvr": "itag=397,type=3,seg=5,range=542581-578653,time=25.6-30.7,off=0,len=36073,end=1",
  "lab": "0.000-20.001",
  "lvb": "0.000-30.720",
  "ismb": 850000,
  "relative_loudness": "-7.423",
  "optimal_format": "720p",
  "user_qual": "auto",
  "debug_videoId": "V86G03930Nc",
  "0sz": false,
  "op": "",
  "yof": false,
  "dis": "",
  "gpu": "Mesa_Intel(R)_UHD_Graphics_620_(KBL_GT2)",
  "cgr": true,
  "debug_playbackQuality": "large",
  "debug_date": "Thu Oct 15 2020 17:45:30 GMT+0800 (Philippine Standard Time)"
}`

Edit: The add-on preference is set to 360p. The debug info came from the video that is automatically set to "Auto" because of the add-on bug.

**Comment by dessant** [comment] 2020-10-15 10:57
I've tested with the latest Firefox on Linux by visiting the first link below and setting the resolution to 360p, then I've visited the second link and started the playback, and the resultion was set to 360p, not auto.

https://topdocumentaryfilms.com/super-comet/
https://topdocumentaryfilms.com/canada-toxic-chemical-valley/

Either YouTube serves different code for you that is not compatible with the extension, or there is a change in your browser profile that triggers a bug.

So after you've set 360p from the video and then opened the extension's options, you see 360p as the preferred quality, even if that setting was different before?

**Comment by ghost** [comment] 2020-10-15 23:30
The extension is set to 360p and it is working on Youtube website. It just could not work to embedded Youtube videos. I guess the extension could not set the quality to "youtube-nocookie" website.

Here is a similar extension that works:
https://addons.mozilla.org/en-US/firefox/addon/youtube-auto-hd-fps/

**Comment by dessant** [comment] 2020-10-16 05:27
This extension depends on the `setPlaybackQualityRange` API of the YouTube player, which is officially deprecated, and it has not been available in the past for embedded videos (see https://github.com/dessant/youtube-video-quality/issues/6), though lately it has started to work for me in various browsers I've tested.

Based on what you said it looks like they aren't always including this API in embedded videos. The extension you shared makes use of the quality setting buttons, we could fall back to something similar when the API is not available.

**Comment by ghost** [comment] 2020-10-19 10:35
Is there plan for this to fix?

**Comment by dessant** [comment] 2020-10-19 10:37
I don't have time for it in the near future, but I'd like to fix it at some point.

**Comment by dessant** [comment] 2023-04-04 07:00
This issue has been fixed in version 2.0.0, the new release will be available on extension stores in the next few days.

**Closed as completed by dessant** 2023-04-04 07:00 UTC
